### ISSUE TITLE
Build me page backend

### ISSUE THREAD

**Issue by lh2510** [agile-dev-assignments/project-setup-team-ikedacho-visionary#262]
This task is part of user story #127

- [x] 1. add `Linked_platform_connect` component. #262 
- [x] 2. add a route for `/me` in `app.js`. #262
- [x] 3.  click `connect` to `unconnect` a social media account from `O-zone` account. #262
- [x] when user click connect button of a linked social media, this social media will be deleted in the linked social media  section.
- [x]  4. `unconnect` a social media account in `Me` page does not influence `linked_social_media` in `My_profile` page(by user_info...). A global `linked_social_media` can be implemented later when we have a database
- [x]  5. make a unique `id` for every `post_data` created. To avoid the messing `post_content` components created by `post_data.map` function, every post must have its unique `id`. Otherwise, there will be some strange repeating componentd created from the map function.

[https://stackoverflow.com/questions/5767325/how-can-i-remove-a-specific-item-from-an-array](url)
[https://stackoverflow.com/questions/4588759/how-do-you-set-a-javascript-onclick-event-to-a-class-with-css](url)
[https://stackoverflow.com/questions/29884654/button-that-refreshes-the-page-on-click](url)
